### ISSUE TITLE
Python libraries missed

### ISSUE THREAD

**Issue by fedyakov** [shadawck/awesome-cli-frameworks#13]
Some actively developing Python libraries that can be added to the list:
- [Clipstick](https://github.com/sander76/clipstick)
- [Clize](https://github.com/epsy/clize)
- [datargs](https://github.com/roee30/datargs)
- [Decli](https://github.com/woile/decli)
- [Plac](https://github.com/ialbert/plac)
- [SimpleParsing](https://github.com/lebrice/SimpleParsing)
- [Typed Argument Parser (Tap)](https://github.com/swansonk14/typed-argument-parser)
- [tyro](https://github.com/brentyi/tyro)

**Comment by shadawck** [comment]
Thank you for this addition 👍

**Comment by uselessscat** [comment]
@shadawck Maybe https://github.com/Textualize/rich can be added also? Its not about parsing but about formatting the cli output, also it has about 50k stars :)
