### ISSUE TITLE
Add an entry

### ISSUE THREAD

**Issue by vincent-thomas** [shadawck/awesome-cli-frameworks#14]
I am a author for a new rust cli framework and would like to let people know it exists. How would I go about adding an entry to this list, would a simple pr be enough?

**Comment by shadawck** [comment]
Hello @vincent-thomas , generally, for new projects, I wait for them to become somewhat known and maintained over time.

**Comment by shadawck** [comment]
If you want to make your project known and share it, you can check out the Rust community on Reddit, for example. (https://www.reddit.com/r/rust/)
