### ISSUE TITLE
Consider adding Ocaml/reasonml

### ISSUE THREAD

**Issue by danielo515** [shadawck/awesome-cli-frameworks#2]
Ocaml is able to build standalone cli tools that have a very good performance.
They also have some good tools to help with this task that are worth listing:
- [cmdliner](https://github.com/dbuenzli/cmdliner): argument parsing
- [Pastel](https://reason-native.com/docs/pastel/): colorize the output

**Comment by shadawck** [comment]
Hello,
I have added, cmdliner, minicli, and clap. 
I think Pastel is a bit out of context.

**Comment by danielo515** [comment]
I only knew cmdliner, thanks for adding them.
I suggested pastel because you already have the JS version on the list.
